services:
    web: # nginx web serveris
        image: nginx:latest
        restart: unless-stopped
        ports:
            #- "82:80"  # replace default ports if using proxy
            - "80:80"
        volumes:
            - ./pagrindinis:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
            - mysql
        depends_on:
            - php-fpm
            - mysql

    #reverse-proxy: # reverse proxy
        #image: 'jc21/nginx-proxy-manager:latest'
        #restart: unless-stopped
        #ports:
        #- '80:80'
        #- '81:81'
        #- '443:443'
        #volumes:
        #- ./proxy/data:/data
        #- ./proxy/letsencrypt:/etc/letsencrypt

    php-fpm: # php priedas nginx'ui
        build: docker/php-fpm
        restart: unless-stopped
        volumes:
            - ./pagrindinis:/var/www/html

    mysql: # duomabze
        image: mysql:latest
        restart: unless-stopped
        command: --init-file /data/application/init.sql
        env_file:
            - mysql.env
        volumes:
            - ./mysql:/var/lib/mysql
            - ./mysql-log:/var/log/mysql
            - ./docker/mysql/init.sql:/data/application/init.sql    
        depends_on:
            - php-fpm

    adminer: # duombazes narsymo irankis
        image: adminer:latest
        restart: unless-stopped
        ports:
            - "8080:8080"
        links:
            - mysql
        