services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./pagrindinis:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

    php-fpm:
        build: php-fpm
        volumes:
            - ./pagrindinis:/var/www/html
