services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./pagrindinis:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
            - mysql
        depends_on:
            - php-fpm
            - mysql

    php-fpm:
        build: php-fpm
        volumes:
            - ./pagrindinis:/var/www/html

    mysql:
        image: mysql:latest
        env_file:
            - mysql.env
        volumes:
            - ./mysql:/var/lib/mysql
            - ./mysql-logs:/var/log/mysql
        depends_on:
            - php-fpm